
# LIBRARY LOAD ------------------------------------------------------------

library(readxl)
library(purrr)
library(dplyr)
library(tidyr)
library(janitor)
library(leaflet)
library(shiny)
library(magrittr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(shinythemes)
library(shinydashboard)
library(leaflet.extras)
library(lubridate)
library(plotly)
library(sf)
library(htmltools)
library(viridis)
library(glue)
library(bsplus)
library(shinycssloaders)
library(gghighlight)
library(shinyjs)
library(scales)
library(leafpop)
library(htmlwidgets)
library(colorspace)
library(zoo)

library(CRplot) #devtools::install_github("CompassRed/CRplot")

readRenviron(".Renviron")

source("utils/num_formatter.R",local = T)
source("utils/paste_log_levels_label.R",local = T)